<?php

 echo $block->sayHello();
$serializedFormData="hello";
?>

  <!DOCTYPE html>
  <html>
  <body>
    <center>
        <h2> Registration page </h2><br>


     <form id="registration" action="<?php echo $block->getBaseUrl().'hello/index/save'; ?>" method="post" onsubmit="return checkForm(this);">
        Name:<br>
        <input type="text" title="name"  name="name" placeholder="Name" ><br><span id="nameerror"></span>
        <br>
        email:<br>
        <input type="text" title="email" name="email" placeholder="Email" required>
        <br>
        Phone Number:<br>

        <input name="phone_number"  title="phone_number" id="phone_number" type="number" placeholder="Phone Number" required>
        <br><span id="message"></span>

        <br>
        Password:<br>
        <input type="password"  title="password" name="password" placeholder="Password" required>
        <br>
        Confirm Password:<br>
        <input type="password" title="confmpass" name="confmpass" placeholder="Confirm Password" required>
        <br>
        Description:<br>
        <textarea id ="description" title="description" name="description" placeholder="Description" rows="4" cols="50" required ></textarea>
        <br><br>
        <input type="submit" value="Register"> <input type="button" value="Back" onclick="">
        <br><br>
      </form>

    </center>
  </body>

  </html>
